name: Create and Merge PR

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate JWT for GitHub App
        id: generate_jwt
        run: |
          echo "Generating JWT..."
          echo "::set-output name=jwt::$(ruby -r 'jwt' -e 'puts JWT.encode({iat: Time.now.to_i, exp: Time.now.to_i + 600, iss: ENV["APP_ID"]}, OpenSSL::PKey::RSA.new(Base64.decode64(ENV["PRIVATE_KEY"])), "RS256")')"
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Get Access Token for Installation
        id: get_token
        run: |
          echo "Fetching installation access token..."
          response=$(curl -X POST -H "Authorization: Bearer ${{ steps.generate_jwt.outputs.jwt }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/app/installations/${{ secrets.INSTALLATION_ID }}/access_tokens)
          echo "::set-output name=token::$(echo $response | jq -r .token)"

      - name: Create a new branch in Gold repo
        run: |
          git clone https://x-access-token:${{ steps.get_token.outputs.token }}@github.com/MRizk01/gold.git
          cd gold
          git checkout -b new-feature-branch
          # Make changes, e.g., add a file
          echo "Sample content" > sample.txt
          git add sample.txt
          git commit -m "Add sample file"
          git push origin new-feature-branch

      - name: Create a Pull Request
        id: create_pr
        run: |
          pr_response=$(curl -X POST -H "Authorization: token ${{ steps.get_token.outputs.token }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/MRizk01/gold/pulls -d '{"title":"Auto-created PR","head":"new-feature-branch","base":"main"}')
          echo "::set-output name=pr_number::$(echo $pr_response | jq -r .number)"

      - name: Merge the Pull Request
        run: |
          curl -X PUT -H "Authorization: token ${{ steps.get_token.outputs.token }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/MRizk01/gold/pulls/${{ steps.create_pr.outputs.pr_number }}/merge -d '{"merge_method":"merge"}'
