name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: '971144'  # Replace with your actual App ID
          private-key: |
            -----BEGIN PRIVATE KEY-----
            MIIEowIBAAKCAQEAo9XorfXzr3WKVrkLaz0rj+Po8goLsykHS7OXiAkJ35zcy6/b
            CrN0rOu0jcYOrWpXhaxulCx7HFCH7QhIuIMd7gR+t54TxwVR1xCTQ1EdPzu7D4CM
            UB4NaeczYl1L51kswQvVRJ3bQGgxE3fareNvHv/CS0OybP/8K3+eRAOMdXUVOYHJ
            5zylwAjsIjaSClyRtu0+JIS6kuwpRilgvHYWPrvraEFF7899dho1T6xJFcTKvKkK
            NyBpcUcdP28W8B3v0uMsPMVYwj2deMZZ3ah+2eaTZoF3nBVgmy4+t477UVazxj1s
            GUr+K5AEehm0ooovcrkswKIHau3TJI3/vQWexwIDAQABAoIBAAqUXZoeL8Y8yNog
            yOP75zw7c2dtzqObGqWAy2A1dTXDY16j1Hk0bWxdLCObjocUPuKa5+kZljmV2bEs
            v8VqchxUnfotcwl/BnHk2B2Yt1LGAKZXnrftuOAF1gOcErK1x3YP1Y3Aw8+86q5f
            Jvfjn+FYkqtZi8QOI7KLYyTxNbi/5FDpsRSncs0xEpS9uICoPdWvPDAJgf50wysf
            VwPGNtobpFSlTZewmRH1Qs/8o9lY0W4FpAAMjysbSR5CpG6shLQ7PgQCG0zH4i0g
            XGA/GfY+uEVbAC8tGVgq6rIWQzSF2LB5otllXl8mcgNgYICfyaxqQ3S6Jl1/bFXj
            GrJQxkECgYEA0vBs1egFGqV2myVIhp8Z8CqvZRsI1bfVjs1TBzTPV0SjS6R2ga4U
            jYUVbtdlMoUgHMHRD4yzssKWFoECTfJC4bvoHczhLR26UBuN6VweilFrLSBG3GqK
            5R2P8fhLiDCgNQY4n81hCVd9r+Ji1TA4UVdJEpWkXLLGch+O660PPhUCgYEAxtWK
            6XNUINeN+YdQ7vcSVD6BfCqH3pEfN0Xfakd0vf1VNcQtWnUi78lv62pG2ynEc36H
            hi2JUBvpZAyYLRX+qWL2FMYGFmq7gFudfYkSSll/2DxaNeuI/8T7hoQqcvWUTfl3
            Se94PxSgiTsjhdvMpbeCf9rNkg9lNhy+Mjji/GsCgYBhM9lzWM/BT64wICYjov1Y
            5tKcTLDtiyEmBQfVskg5dq+pE8hoSce+zyzpPuirNx1tIwMrnzLPlUuEYz6knJal
            Xum/kcHSAHjyoT/r4T9RjeNNkCoXOCF5Iv5KCpkD0SSCSrOdMA8fNun8Ot5AT1Ak
            a4yIu9xZuygnPtOlVsJHYQKBgQCF49gFub5l2yDkbYVHVSKHjgudc/pIGkr96lQ2
            eeWX5hZR/UdZCVW8SFXQHaGXBTofV42lAdbcFd+EmqKCgbQZleUFOg9xWu/l0Ett
            9DZX0IqxLnrEolV/fcKt4yO+g7YZB6qXI+VB/P7ZSfRyt/7HfJooxEr3Vtydop9E
            rF/U/wKBgEO4RodgNP6o+pQRPt4Pd/rrjQBNvNBRn6o8lumGA7Ty4e0CGlOfGPzS
            /ApzqvGRqvGqGeLMQQbgUr9QUA9DvKQYLMTZXEDd+VB7vzS80KIAPWUBqzsYr03U
            5MNIXOc3kzg9JS8mYscSVDiy9e4Zh0sECbXzU2/WxcvmOhqqv4Gj
            -----END PRIVATE KEY-----
          owner: MRizk01
          repositories: 'MRizk01/gold'
          skip-token-revoke: true

      - name: Create a new branch in Gold repo
        run: |
          git clone https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/MRizk01/gold.git
          cd gold
          git checkout -b new-feature-branch
          # Make changes, e.g., add a file
          echo "Sample content" > sample.txt
          git add sample.txt
          git commit -m "Add sample file"
          git push origin new-feature-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: MRizk01/gold
          title: My Pull Request
          body: This is a pull request created by GitHub Actions
          head: new-feature-branch
          base: main
